'use strict';
// The public website is a guided product preview, not the signed-in PawQi app.
// No visitor inputs, records or questions are persisted or sent to an AI service.
const betaUrl = 'https://pawqi-next-dev-2026.web.app/#/home';
const pets = {
 dog:{guide:'Milo',name:'Bruno',singular:'dog',label:'Dogs',image:'dog.webp',hint:'A dog\u2019s journey, with Milo available when you need help.'},
 cat:{guide:'Mili',name:'Momo',singular:'cat',label:'Cats',image:'cat.webp',hint:'The cat-care journey, with Mili available when you need help.'},
 fish:{guide:'Nemo',name:'Bubbles',singular:'fish',label:'Fish',image:'fish.webp',hint:'Fish care in a calmer aquatic atmosphere, with Nemo as your guide.'},
 bird:{guide:'Mithu',name:'Pip',singular:'bird',label:'Birds',image:'bird.webp',hint:'The bird-care journey in an aviary-inspired atmosphere, with Mithu.'},
 rabbit:{guide:'Popi',name:'Coco',singular:'rabbit',label:'Rabbits',image:'rabbit-popi.webp',hint:'The rabbit-care journey, with Popi available when you need help.'},
 small:{guide:'Tiku',name:'Poppy',singular:'small pet',label:'Small pets',image:'smallpet.webp',hint:'The small-pet journey, with Tiku available when you need help.'}
};
// Text reflects the owner's feature plan, including development/release boundaries.
const features = {
 match:{title:'Pet Match Advisor',chapter:'know',status:'Development verified in PawQi Next',benefit:'Start with your family, lifestyle, home, budget, experience, children and other pets before choosing a pet.',current:'The Pet Planning Advisor supports a private household-planning journey in the beta.',boundary:'Breed and species recommendations remain unavailable until reviewed lifestyle content is approved. This website does not calculate a compatibility score.'},
 reality:{title:'Pet Reality Check',chapter:'know',status:'Prototype complete; reviewed guidance gated',benefit:'Understand the commitment behind pet parenting: time, routine, home, costs and ongoing care.',current:'The plan describes an explainable reality-check prototype using synthetic content.',boundary:'Real recommendations require qualified review and approved sources. No costs, suitability predictions or breed-specific advice are generated here.'},
 vault:{title:'Pet Medical Vault',chapter:'know',status:'Development-verified foundation',benefit:'Keep prescriptions, reports, vaccination records, scans, invoices and medical history with the right pet.',current:'Owner-controlled records and bounded provider-sharing requests are developed in PawQi Next. Documents and prescriptions have distinct navigation.',boundary:'Actual provider record access remains gated. A sharing request is not an active grant. Prescription transcription is a development foundation, not a live feature of this website.'},
 command:{title:'PawQi Pet Command Center',chapter:'care',status:'Development verified in PawQi Next',benefit:'See today\u2019s actions, pending plans and upcoming items in one place, then return directly to the source record.',current:'The beta connects owner-scoped care events, reminders, recorded schedules, calendar items and saved records. Sources are explicitly labelled.',boundary:'A customer reminder is not a medical determination. The website dashboard is an illustrative interaction and does not save tasks or issue notifications.'},
 health:{title:'Pet Health Plan',chapter:'care',status:'Development verified; clinical content gated',benefit:'Connect your recorded preventive-care dates and plans with reminders you explicitly choose to create.',current:'Care-reminder persistence and the preventive-plan experience are developed in the isolated beta.',boundary:'Real veterinary guidance depends on approved sources and qualified review. PawQi does not invent vaccine or medication schedules, prescribe treatment or calculate doses here.'},
 intelligence:{title:'Pet Health Intelligence / Health Graph',chapter:'care',status:'Prototype complete; medical interpretation gated',benefit:'Make the origin of pet-care information clear, including missing or insufficient data.',current:'The beta distinguishes owner-saved records from reminders and avoids presenting an unsupported health score.',boundary:'Real pathway comparisons require approved medical content. This website does not diagnose, predict disease or decide whether vaccination care is complete.'},
 training:{title:'Breed & Age Training Coach',chapter:'care',status:'Development verified; tailored guidance gated',benefit:'Bring your training goals, practice routine and progress into the same care journey.',current:'Owner-controlled goals, progress and explicit reminders are developed in PawQi Next.',boundary:'Breed- and age-specific guidance remains unavailable until governed sources and qualified review are approved. The website does not act as a professional trainer.'},
 nutrition:{title:'Personalised Nutrition Plan',chapter:'care',status:'Nutrition Routine developed in PawQi Next',benefit:'Keep meal, treat, hydration and appetite observations together with your feeding notes.',current:'The beta supports owner-controlled nutrition routines. Portion notes come from the owner, veterinarian or product label.',boundary:'Automatic portions, therapeutic diets, allergy inference and supplement recommendations are not provided. Personalised nutrition guidance requires veterinary nutrition review.'},
 grooming:{title:'Pet Grooming Plan',chapter:'care',status:'Development verified in PawQi Next',benefit:'Track grooming history, organise a plan and keep reminders tied to dates you choose.',current:'Owner-controlled grooming plans, history and explicit reminders are developed in the beta.',boundary:'PawQi does not invent a grooming frequency. Packages, provider availability and completed service booking are not guaranteed by this preview.'},
 vet:{title:'Vet Connect',chapter:'services',status:'Development-verified foundation',benefit:'Go from your pet profile to a coherent veterinary-care pathway instead of searching through disconnected menus.',current:'The beta hub connects reviewed provider discovery, supported appointment requests, Medical Vault sharing controls and emergency discovery.',boundary:'Tele-vet/video clinical consultation and active provider access to medical records remain gated. This website neither provides clinical advice nor confirms appointments.'},
 sitting:{title:'Pet Sitting & Day Care',chapter:'services',status:'Development verified; service operations gated',benefit:'Explore short-term help for the hours when you cannot be there.',current:'Pet-profile actions in PawQi Next open reviewed sitter and day-care discovery using existing provider and appointment-request foundations.',boundary:'The real provider cohort, availability, category-specific checks, fulfilment and payments remain release requirements. A request is not a confirmed stay.'},
 services:{title:'Pet Care Services',chapter:'services',status:'Development verified; fulfilment gated',benefit:'Find the right category of help: walkers, sitters, groomers, trainers, cleaners, boarding and other care professionals.',current:'The beta connects pet profiles to a reviewed provider catalogue; unverified providers remain private.',boundary:'Live availability, service fulfilment, reviews, disputes and payments remain upcoming controlled releases. No booking is made on this website.'},
 journal:{title:'Pet Life Journal',chapter:'life',status:'Development verified in PawQi Next',benefit:'Keep photos, videos, milestones, memories, trips and achievements in your pet\u2019s life timeline.',current:'Owner-only journal persistence and media lifecycle are developed in the beta.',boundary:'The public website shows sample entries only. It does not upload media or expose private journal content.'},
 community:{title:'Pet Community',chapter:'life',status:'Prototype complete; public community gated',benefit:'Connect with local and breed-specific pet parents for discussion, experiences, playdates and celebrations.',current:'Community surfaces have a responsive local/synthetic prototype in PawQi Next.',boundary:'Public community remains disabled pending safety operations, moderation, adult assurance, server-controlled writes and deployment approval.'},
 events:{title:'Pet Events Hub',chapter:'life',status:'Information prototype; real events gated',benefit:'Discover pet shows, adoption drives, vaccination camps, competitions and local meetups.',current:'The beta has category filtering and a reviewed-source catalogue contract using synthetic examples.',boundary:'Live organizer onboarding and event discovery are not active here. This website makes no ticketing, availability, attendance or organizer-endorsement claim.'},
 emergency:{title:'Pet Emergency Button',chapter:'future',status:'Beta foundation plus public external-search tool',benefit:'Keep an emergency pathway easy to reach, without making visitors finish onboarding first.',current:'The website opens an external emergency-vet search without login. Private contacts and reviewed provider filters belong to the signed-in beta.',boundary:'External results are not PawQi-verified. First-aid and poison guidance require reviewed content. This is not emergency dispatch, a response-time guarantee or clinical advice.'},
 lost:{title:'Lost & Found Network',chapter:'future',status:'Private preparation developed; public alerts gated',benefit:'Prepare pet identity and last-seen information so important details are not scattered.',current:'The beta supports owner-private approximate area, last-seen time and notes for the primary pet.',boundary:'Public alerts, relay, moderation, community notifications, QR contact tags and GPS integrations remain gated. Saving notes does not notify anyone.'},
 travel:{title:'Travel Assistant',chapter:'future',status:'Private trip planning developed',benefit:'Keep origin, destination, travel mode, dates and preparation notes together with your pet.',current:'The beta supports private trip-plan persistence and neutral preparation checklists.',boundary:'PawQi does not book travel, guarantee acceptance or issue health/travel documents. Carrier and jurisdiction guidance require current official sources and approval.'},
 civic:{title:'Pet Civic Assistant',chapter:'future',status:'Development verified in PawQi Next',benefit:'Track your document tasks, jurisdiction, issuing authority and renewal dates.',current:'The beta stores owner-controlled tasks and official source links, with separate reminders from dates the owner confirms.',boundary:'PawQi does not determine municipal requirements, claim government integration or legally verify documents. Official catalogues remain governed-source work.'},
 insurance:{title:'Pet Insurance Advisor',chapter:'future',status:'Insurance Organizer foundation developed',benefit:'Keep the policy and claim-document information you record in one organised place.',current:'The beta includes an owner-entered claim-document tracker, grouped by insurer and claim reference.',boundary:'Insurer connections, eligibility decisions, claim submission and outcomes are not provided here. Real policy comparison and commercial/legal controls remain gated.'},
 guardian:{title:'Pet Guardian Plan',chapter:'future',status:'Private preparation developed',benefit:'Prepare primary and backup contacts, care instructions and future-care preferences.',current:'PawQi Next keeps Primary and Backup as independent owner-controlled preparation slots.',boundary:'Saving a name sends no invitation and grants no account, medical, legal or financial authority. Acceptance, activation and legal review remain gated.'},
 pregnancy:{title:'Pre & Post Pregnancy Support',chapter:'future',status:'Private record foundation developed',benefit:'Keep reproductive-care observations together for your pet\u2019s ongoing care conversations.',current:'The beta supports owner/pet-scoped private observations.',boundary:'It does not confirm pregnancy or give clinical advice. Treating-veterinarian workflows and reviewed clinical guidance remain gated.'},
 adoption:{title:'Pet Adoption Support',chapter:'future',status:'Development foundation; applications not open',benefit:'Support the journey toward finding an appropriate home through a governed adoption pathway.',current:'Secure application transport has been verified in isolated development.',boundary:'Applications remain closed until a verified rescue cohort, screening process and support ownership are approved. This website does not list real adoptable pets.'},
 marketplace:{title:'Pet Nutrition Marketplace',chapter:'future',status:'Synthetic preview; real commerce gated',benefit:'Explore the future connection between nutritional profiles and reviewed fresh/customised pet-food providers.',current:'The beta contains a nutrition-specific synthetic marketplace preview with ingredient and source-review controls.',boundary:'Real suppliers, ordering, delivery, nutrition matching, medical-suitability claims and payments are not active.'},
 legacy:{title:'Pet Legacy & End-of-Life Support',chapter:'future',status:'Private Comfort & Legacy foundation developed',benefit:'Prepare care-conversation notes, document checklists, researched contacts and memorial preferences privately.',current:'Owner-controlled Comfort & Legacy planning is developed across the beta.',boundary:'No prognosis, quality-of-life score, euthanasia recommendation, grief counselling, service booking or local legality claim is provided. Sensitive decisions need qualified professionals.'},
 partners:{title:'For Vets & Pet-care Partners',chapter:'services',status:'Partner pathway; controlled rollout',benefit:'Connect provider discovery with the wider pet-parent care journey.',current:'Explore the PawQi beta and the provider-discovery experience before continuing a partner journey.',boundary:'This website does not verify a professional, activate medical-record access or enrol a provider. Appropriate verification and operating approvals remain necessary.'}
};
const $=s=>document.querySelector(s), $$=s=>Array.from(document.querySelectorAll(s));
let activePet='dog', currentChapter='know', activeTab='today', activeService='vet', toastTimer, lastDialogTrigger;
const completed = new Set();
const chapters={know:'Pet profiles & records',care:'Your daily care plan',services:'Finding care',life:'Memories & community',future:'Future-care planning'};
function node(tag,text,cls){const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(cls)e.className=cls;return e;}
function showToast(text){clearTimeout(toastTimer);$('#toast').textContent=text;$('#toast').hidden=false;toastTimer=setTimeout(()=>$('#toast').hidden=true,4800);}
function dismissWelcome(){$('#guideWelcome').hidden=true;}
function openDialog(d){if(!document.activeElement.closest('dialog'))lastDialogTrigger=document.activeElement;$$('dialog[open]').forEach(x=>x.close());dismissWelcome();d.showModal();}
function closeDialog(d){d.close();if(lastDialogTrigger&&lastDialogTrigger.isConnected)lastDialogTrigger.focus();}
$$('[data-close]').forEach(b=>b.addEventListener('click',()=>closeDialog(b.closest('dialog'))));
$$('dialog').forEach(d=>d.addEventListener('click',e=>{if(e.target!==d)return;const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)closeDialog(d);}));
function visitChapter(id){$$('dialog[open]').forEach(d=>d.close());dismissWelcome();const section=document.getElementById(id);if(section){section.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'});section.setAttribute('tabindex','-1');section.focus({preventScroll:true});}}
function featureButton(id,label){const b=node('button',label,'text-button');b.addEventListener('click',()=>showFeature(id));return b;}
function showFeature(id){const f=features[id];if(!f)return;$('#featureTitle').textContent=f.title;$('#featureKicker').textContent='PAWQI FEATURE · '+chapters[f.chapter].toUpperCase();const box=$('#featureContent');box.replaceChildren(node('span',f.status,'feature-status'),node('p',f.benefit),node('h3','What the product plan supports'),node('p',f.current),node('div',f.boundary,'boundary'));const actions=node('div',undefined,'actions');const explore=node('button','See this in the journey ↓','button secondary');explore.addEventListener('click',()=>visitChapter(f.chapter));const link=node('a','Open PawQi beta ↗','button primary');link.href=betaUrl;link.target='_blank';link.rel='noopener';actions.append(explore,link);box.append(actions,node('p','Status follows the supplied PawQi feature plan, last updated through 7 September 2026. Development verification is not a public-production availability guarantee.','micro'));if(id==='match')box.append(featureButton('reality','Also explore Pet Reality Check →'));openDialog($('#featureDialog'));}
$$('[data-feature]').forEach(b=>b.addEventListener('click',()=>showFeature(b.dataset.feature)));
function renderCatalog(){const q=$('#featureSearch').value.trim().toLowerCase();const found=Object.entries(features).filter(([,f])=>(f.title+' '+f.benefit+' '+f.current).toLowerCase().includes(q));$('#catalogCount').textContent=found.length+' features and pathways';const results=$('#catalogResults');results.replaceChildren();for(const [id,f] of found){const b=node('button',undefined,'catalog-row');const text=node('span');text.append(node('b',f.title),node('small',chapters[f.chapter]));b.append(text,node('span','→'));b.addEventListener('click',()=>showFeature(id));results.append(b);}if(!found.length)results.append(node('p','No matching feature. Try records, training, travel or care.'));}
function openCatalog(){openDialog($('#catalogDialog'));$('#featureSearch').value='';renderCatalog();$('#featureSearch').focus();}
$$('[data-catalog]').forEach(b=>b.addEventListener('click',openCatalog));$('#featureSearch').addEventListener('input',renderCatalog);
function sampleItems(){const sp=pets[activePet].singular;const habitat=['fish','bird','small'].includes(activePet);return {today:[['review','Review a saved care record','Your saved medical record','Recorded information'],['routine','Review today\u2019s routine','Your chosen routine','Owner-entered plan'],['plan','Check an upcoming reminder','The date you selected','Customer reminder']],routines:[['food','Add a feeding observation','Your '+sp+'\u2019s owner-recorded notes','Nutrition Routine'],['practice',habitat?'Record habitat observations':'Review a training goal',habitat?'Your habitat notes':'Your chosen practice goal',habitat?'Owner observation':'Training Coach'],['groom',habitat?'Review a habitat-care note':'Review grooming history','Recorded dates, not generated schedules',habitat?'Owner observation':'Grooming Plan']],records:[['vax',habitat?'Review a care document':'Review a vaccination record','Owner-saved; not clinically verified','Medical Vault'],['rx','Find a prescription or report','Example saved document','Medical Vault'],['journal','Open a journal memory','Example private journal entry','Pet Life Journal']]};}
function renderTasks(){const panel=$('#carePanel');panel.replaceChildren();for(const [id,title,desc,source] of sampleItems()[activeTab]){const key=activePet+':'+activeTab+':'+id;const done=completed.has(key);const b=node('button',undefined,'task-row');b.setAttribute('aria-pressed',String(done));b.append(node('span',done?'✓':'','task-check'));const content=node('span');content.append(node('b',title),node('small',desc));b.append(content,node('span',source,'source'));b.addEventListener('click',()=>{completed.has(key)?completed.delete(key):completed.add(key);renderTasks();const btn=panel.querySelector('[data-task="'+id+'"]');if(btn)btn.focus();});b.dataset.task=id;panel.append(b);}const count=sampleItems()[activeTab].filter(([id])=>completed.has(activePet+':'+activeTab+':'+id)).length;$('#taskStatus').textContent=count+' of 3 sample tasks checked · Not saved';}
function switchTab(key){if(!['today','routines','records'].includes(key))return;activeTab=key;$$('[data-tab]').forEach(b=>{const on=b.dataset.tab===key;b.setAttribute('aria-selected',String(on));b.tabIndex=on?0:-1;});$('#carePanel').setAttribute('aria-labelledby','tab-'+key);renderTasks();}
$$('[data-tab]').forEach((b,i)=>{b.addEventListener('click',()=>switchTab(b.dataset.tab));b.addEventListener('keydown',e=>{const tabs=$$('[data-tab]');let target;if(e.key==='ArrowRight')target=(i+1)%tabs.length;if(e.key==='ArrowLeft')target=(i+tabs.length-1)%tabs.length;if(e.key==='Home')target=0;if(e.key==='End')target=tabs.length-1;if(target!==undefined){e.preventDefault();switchTab(tabs[target].dataset.tab);tabs[target].focus();}});});$('#resetTasks').addEventListener('click',()=>{for(const k of completed){if(k.startsWith(activePet+':'))completed.delete(k);}renderTasks();showToast('Sample tasks reset. No saved care records were changed.');});
function updateService(id){activeService=id;$$('[data-service]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.service===id)));const f=features[id];$('#serviceDetail').replaceChildren(node('h4',f.title),node('p',f.benefit));$('#serviceExplore').textContent='Explore '+f.title+' →';}
$$('[data-service]').forEach(b=>b.addEventListener('click',()=>updateService(b.dataset.service)));$('#serviceExplore').addEventListener('click',()=>showFeature(activeService));
function message(text,who='assistant'){const area=$('#guideMessages');area.append(node('div',text,'message '+who));while(area.children.length>20)area.firstElementChild.remove();area.scrollTop=area.scrollHeight;}
function hello(){return 'Hi, I\u2019m '+pets[activePet].guide+', your PawQi assistant. I can help you find features in the '+pets[activePet].singular+'-care journey. What would you like to explore?';}
function openGuide(){openDialog($('#guideDialog'));if(!$('#guideMessages').children.length)message(hello());$('#guideInput').focus();}
$('#guideLauncher').addEventListener('click',openGuide);$('#dismissWelcome').addEventListener('click',dismissWelcome);
$('#petSpecies').addEventListener('change',e=>{const next=e.target.value;if(!pets[next])return;const prior=pets[activePet].guide;activePet=next;const p=pets[next];document.body.dataset.pet=next;$$('[data-pet-name]').forEach(x=>x.textContent=p.name);$$('[data-initial]').forEach(x=>x.textContent=p.name[0]);$$('[data-pet-description]').forEach(x=>x.textContent='Example '+p.singular+' profile · Your records, your routine');$$('[data-species-singular]').forEach(x=>x.textContent=p.singular);$('#speciesHint').textContent=p.hint;$('#guideName').textContent='Ask '+p.guide;$('#guideTitle').textContent=p.guide;$('#guideHint').textContent='Your '+p.singular+'-care guide';$('#guidePhoto').src='assets/'+p.image;$('#chatPhoto').src='assets/'+p.image;$('#guideMessages').replaceChildren();message(hello());dismissWelcome();renderTasks();showToast(next==='dog'?'Milo is back to guide your dog-care journey.':prior+': For '+p.label.toLowerCase()+', '+p.guide+' will help you explore.');});
$$('[data-guide-target]').forEach(b=>b.addEventListener('click',()=>visitChapter(b.dataset.guideTarget)));
function detectFeature(q){if(/emergency|urgent|sos|poison|cannot breathe|can't breathe/.test(q))return'emergency';const rules=[['lost',/lost|missing|gps/],['guardian',/guardian|backup|if i die/],['vet',/\bvet\b|doctor|consult/],['vault',/prescription|vault|document|scan|medical record/],['command',/command|dashboard|today|remind/],['health',/health|vaccin|medicine|medication|deworm/],['training',/train|behavio|bark|toilet/],['nutrition',/food|nutri|meal|hydration|feeding/],['grooming',/groom|bath|nail/],['sitting',/sitting|sitter|day care|daycare/],['services',/service|boarding|walker|walking/],['journal',/journal|memory|photo|video/],['community',/community|friend|circle/],['events',/event|meetup/],['travel',/travel|trip|flight/],['civic',/civic|municip|licen|renewal/],['insurance',/insur|claim/],['pregnancy',/pregnan|litter/],['adoption',/adopt|rescue/],['legacy',/legacy|end.of.life|memorial/],['match',/match|choos|pet.ready|new pet/]];return rules.find(([,r])=>r.test(q))?.[0];}
$('#guideForm').addEventListener('submit',e=>{e.preventDefault();const input=$('#guideInput');const text=input.value.trim();if(!text)return;message(text,'user');input.value='';const id=detectFeature(text.toLowerCase());if(id==='emergency'){message('Emergency help is available without login. Opening the external-search pathway now.');openDialog($('#emergencyDialog'));$('#emergencyLocation').focus();return;}if(id){const f=features[id];message(f.benefit+'\n\nIn this preview: '+f.boundary);const b=featureButton(id,'Explore '+f.title+' →');$('#guideMessages').append(b);$('#guideMessages').scrollTop=$('#guideMessages').scrollHeight;}else message('I\u2019m a scripted website guide, not a live AI service yet. I can explain PawQi features and help you find the right section. Try records, training, grooming, care services, travel or guardian planning.');});
$$('[data-emergency]').forEach(b=>b.addEventListener('click',()=>{openDialog($('#emergencyDialog'));$('#emergencyLocation').focus();}));
$('#emergencyForm').addEventListener('submit',e=>{e.preventDefault();const place=$('#emergencyLocation').value.trim();if(!place){$('#emergencyLocation').setCustomValidity('Enter a city or area.');$('#emergencyLocation').reportValidity();return;}const url='https://www.google.com/maps/search/?api=1&query='+encodeURIComponent('emergency veterinarian '+place);window.open(url,'_blank','noopener,noreferrer');});$('#emergencyLocation').addEventListener('input',()=>$('#emergencyLocation').setCustomValidity(''));
$$('[data-privacy]').forEach(b=>b.addEventListener('click',()=>{$('#featureKicker').textContent='ABOUT THIS WEBSITE';$('#featureTitle').textContent='Explore first. Keep private care private.';$('#featureContent').replaceChildren(node('p','This public PawQi website is a product and interaction preview. Questions and sample tasks are held only in this page; we do not save them or send them to an AI backend.'),node('div','There is no diagnosis, medicine-dose calculation, checkout, appointment confirmation or emergency dispatch here. Emergency search opens external, unverified Maps results.','boundary'),node('p','PawQi Next links open the development beta supplied by the project owner. Its sign-in, data handling and service availability are separate from this website. This explanation is not a substitute for the approved production Privacy Policy or Terms.','micro'));openDialog($('#featureDialog'));}));
$('#menuButton').addEventListener('click',()=>{const open=!$('.header').classList.contains('menu-open');$('.header').classList.toggle('menu-open',open);$('#menuButton').setAttribute('aria-expanded',String(open));$('#menuButton').setAttribute('aria-label',open?'Close menu':'Open menu');});
$('#mainNav').addEventListener('click',()=>{$('.header').classList.remove('menu-open');$('#menuButton').setAttribute('aria-expanded','false');$('#menuButton').setAttribute('aria-label','Open menu');});
// Track reading progress without moving the visitor or opening the assistant.
let scheduled=false;function onScroll(){if(scheduled)return;scheduled=true;requestAnimationFrame(()=>{scheduled=false;const sections=$$('[data-step]');let chapter='know';for(const s of sections){if(s.getBoundingClientRect().top<innerHeight*.45)chapter=s.dataset.step;}currentChapter=chapter;$$('[data-chapter]').forEach(a=>{if(a.dataset.chapter===chapter)a.setAttribute('aria-current','step');else a.removeAttribute('aria-current');});const denom=document.documentElement.scrollHeight-innerHeight;$('#readingProgress').style.width=Math.max(0,Math.min(100,denom>0?scrollY/denom*100:0))+'%';$('#guideHint').textContent=chapters[chapter];if(scrollY>180)dismissWelcome();});}addEventListener('scroll',onScroll,{passive:true});
if('IntersectionObserver'in window){const observer=new IntersectionObserver(entries=>{for(const e of entries){if(e.isIntersecting){e.target.classList.add('revealed');observer.unobserve(e.target);}}},{threshold:.08});$$('.chapter-title').forEach(x=>observer.observe(x));}
// Image decode failures never hide a call to action.
$$('#guidePhoto,#chatPhoto').forEach(img=>img.addEventListener('error',()=>{img.hidden=true;}));
renderTasks();updateService('vet');
